Fix CPU clock
brain-hackers/u-boot-brain pull request #27
Opened 2024-01-29 10:58 UTC by UnagiDojyou

SDカードから直接起動する際にCPUのクロックが半分となってしまう問題を治しました。
PW-SA1で動作を確認しました。

2024-01-31 05:05 UTC, puhitaku requested changes
インデントの修正をお願いします。コミットメッセージが "first commit" になっているので、同じディレクトリのファイルを含めて周囲のコミットを見てみて、それっぽいコミットメッセージにしてみましょう

2024-01-31 05:05 UTC, puhitaku commented on board/sharp/common/cpu_clkdiv.c
一部のインデントがスペースになっているので他のコードを参考に Tab に直してください

2024-02-01 12:01 UTC, UnagiDojyou commented on board/sharp/common/cpu_clkdiv.c
修正しました。

2024-02-04 00:53 UTC, puhitaku approved these changes
![f6232839-1a8b-4ca6-9c9b-86be1203014e](https://github.com/brain-hackers/u-boot-brain/assets/2425178/7e58fca0-82db-4db4-8f1c-d1a564fb9407)

2024-02-04 00:53 UTC, merged